### ISSUE TITLE
你好,几个建议.

### ISSUE THREAD

**Issue by BaanX** [CaiJingLong/flutter_long_tap_menu#1]
1.最多只能显示一行,我这里是五个item,超过无法显示.
2.item之间距离过大,不太美观.

**Comment by CaiJingLong** [comment]
update version 0.1.2, and see README.

You can use `decoration` or `itemBuilder` to custom your item.

For items beyond one screen, scroll horizontally to see more items
Normally, this pop-up menu option should not be too many.

**Comment by BaanX** [comment]
收到,我试试,非常感谢.
